services:
  - type: web
    name: policy-reader
    env: python
    runtime: python-3.11.9
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install torch --index-url https://download.pytorch.org/whl/cpu
      pip install --no-cache-dir -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: policy-reader
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
